name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: build
      run: mvn clean package -DskipTests=true
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
        
    - name: Schedule test run with mixed data
      uses: realm/aws-devicefarm/test-application@master
      with:
        name: schedule-run
        project_arn: ${{ secrets.AWS_PROJECT_ARN }}
        device_pool_arn: ${{ secrets.AWS_DEVICE_POOL_ARN }}
        app_file: ${{ github.workspace }}\aut\Coffee Timer.ipa
        app_type: IOS_APP
        test_type: APPIUM_JAVA_JUNIT
        test_package_file: ${{ github.workspace }}\target\zip-with-dependencies.zip
        test_package_type: APPIUM_JAVA_JUNIT_TEST_PACKAGE
        remote_src: true
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
