name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: build
      run: mvn clean package -DskipTests=true
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
        
    - name: Schedule test run with mixed data
      uses: realm/aws-devicefarm/test-application@master
      with:
        name: schedule-run
        project_arn: ${{ secrets.AWS_PROJECT_ARN }}
        device_pool_arn: ${{ secrets.AWS_DEVICE_POOL_ARN }}
        app_file: ${{ github.workspace }}\aut\Coffee Timer.ipa
        app_type: IOS_APP
        test_type: APPIUM_JAVA_JUNIT
        test_package_file: ${{ github.workspace }}\target\zip-with-dependencies.zip
        test_package_type: APPIUM_JAVA_JUNIT_TEST_PACKAGE
        test_spec: |
          version: 0.1
          phases:
            install:
              commands:
                - export JAVA=8

            pre_test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant fi.aardsoft.devicefarmsample android.permission.READ_EXTERNAL_STORAGE
                - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant fi.aardsoft.devicefarmsample android.permission.WRITE_EXTERNAL_STORAGE

            test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID shell am instrument -w -r -e foo bar -e bar baz fi.aardsoft.devicefarmsample

            post_test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID pull /storage/emulated/0/Android/data/fi.aardsoft.devicefarmsample/files/output.txt
                - mv output.txt $DEVICEFARM_LOG_DIR/test-output.txt

          artifacts:
            - $DEVICEFARM_LOG_DIR
        remote_src: true
        
      
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
